version: "3.8"

services:
  powershell-engine:
    build: .
    ports:
      - "4042:4042"
    environment:
      LOG_LEVEL: WARNING
      GUNICORN_TIMEOUT: 3600
      GUNICORN_KEEPALIVE: 120
    restart: always
